development:
  adapter: postgresql
  encoding: unicode
  database: rainbowtext_development
  pool: 5
  username: aneer
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: rainbowtext_test
  pool: 5
  username: aneer
  password: 

